import type {
  AppTenant,
  AppUser,
  CatalogItem,
  ClassSummary,
  FeedbackItem,
  Membership,
  PageEnvelope,
  PathSummary,
  StudentDashboardData,
  StudentProgressData,
  StudentSummary,
  SubmissionSummary,
  TaskDetail,
  TaskItem,
  TeacherDashboardData,
} from './types';

export const demoUser: AppUser = {
  id: '01900000-0000-7000-8000-000000000001',
  displayName: '林晓然',
  email: 'xiaoran@example.com',
};

export const demoTenants: AppTenant[] = [
  {
    id: '01900000-0000-7000-8000-000000000101',
    name: '海岚国际英语',
    slug: 'hailan-english',
    membershipId: '01900000-0000-7000-8000-000000000111',
    roles: ['student', 'teacher', 'admin'],
  },
  {
    id: '01900000-0000-7000-8000-000000000102',
    name: '远望语言中心',
    slug: 'farview-language',
    membershipId: '01900000-0000-7000-8000-000000000112',
    roles: ['teacher', 'content_editor'],
  },
];

export const demoTasks: TaskItem[] = [
  {
    id: 'task-reading-01',
    title: 'TOEFL 阅读 · 推断题专项',
    kind: 'practice',
    workflowState: 'in_progress',
    availability: 'available',
    dueAt: '2026-07-12T12:00:00Z',
    availableAt: '2026-07-09T00:00:00Z',
    isOverdue: false,
    isLate: false,
    sourceCount: 2,
    sourceLabel: 'TOEFL 路径 · A2 班',
    estimatedMinutes: 28,
  },
  {
    id: 'task-writing-01',
    title: '独立写作 · 城市公共空间',
    kind: 'writing',
    workflowState: 'returned',
    availability: 'available',
    dueAt: '2026-07-13T14:00:00Z',
    availableAt: '2026-07-08T00:00:00Z',
    isOverdue: false,
    isLate: false,
    sourceCount: 1,
    sourceLabel: '周老师 · 个人任务',
    estimatedMinutes: 36,
  },
  {
    id: 'task-general-01',
    title: 'General · 学术词汇回顾',
    kind: 'lesson',
    workflowState: 'not_started',
    availability: 'available',
    dueAt: '2026-07-15T12:00:00Z',
    availableAt: '2026-07-10T00:00:00Z',
    isOverdue: false,
    isLate: false,
    sourceCount: 1,
    sourceLabel: 'General 基础路径',
    estimatedMinutes: 18,
  },
  {
    id: 'task-listening-01',
    title: '讲座听力 · 结构识别',
    kind: 'assessment',
    workflowState: 'grading',
    availability: 'available',
    dueAt: '2026-07-10T12:00:00Z',
    availableAt: '2026-07-07T00:00:00Z',
    isOverdue: false,
    isLate: false,
    sourceCount: 1,
    sourceLabel: 'TOEFL 冲刺班',
    estimatedMinutes: 24,
  },
  {
    id: 'task-completed-01',
    title: '句子结构 · 从句辨析',
    kind: 'practice',
    workflowState: 'completed',
    availability: 'available',
    dueAt: '2026-07-08T12:00:00Z',
    availableAt: '2026-07-04T00:00:00Z',
    isOverdue: false,
    isLate: false,
    sourceCount: 1,
    sourceLabel: 'General 基础路径',
    estimatedMinutes: 20,
  },
];

export const demoTaskPage: PageEnvelope<TaskItem> = {
  data: demoTasks,
  page: { nextCursor: null, limit: 20 },
};

export const demoTaskDetail: TaskDetail = {
  item: demoTasks[0]!,
  taskSnapshot: {
    id: 'task-version-reading-01',
    versionNumber: 3,
    title: 'TOEFL 阅读 · 推断题专项',
    instructions: '阅读短文并完成 3 道题。答案会自动保存，提交后进入自动评分。',
    kind: 'practice',
    contentHash: 'sha256:demo-reading-v3',
    questions: [
      {
        questionVersionId: 'question-reading-01',
        kind: 'single_choice',
        prompt: 'According to the passage, why did early urban planners favor public squares?',
        options: [
          { id: 'a', label: 'A', content: 'They reduced construction costs.' },
          { id: 'b', label: 'B', content: 'They supported civic exchange.' },
          { id: 'c', label: 'C', content: 'They replaced private housing.' },
          { id: 'd', label: 'D', content: 'They improved rail efficiency.' },
        ],
        position: 0,
        maxScore: 1,
      },
      {
        questionVersionId: 'question-reading-02',
        kind: 'multiple_choice',
        prompt: 'Which TWO claims are supported by the passage?',
        options: [
          { id: 'a', label: 'A', content: 'Public space can strengthen trust.' },
          { id: 'b', label: 'B', content: 'Every square needs commercial use.' },
          { id: 'c', label: 'C', content: 'Design affects patterns of meeting.' },
          { id: 'd', label: 'D', content: 'Dense cities eliminate public life.' },
        ],
        position: 1,
        maxScore: 2,
      },
      {
        questionVersionId: 'question-reading-03',
        kind: 'short_text',
        prompt: '用 1–2 句英文概括作者对公共空间的核心观点。',
        options: [],
        position: 2,
        maxScore: 2,
      },
    ],
  },
  attempt: {
    id: 'attempt-reading-01',
    attemptNumber: 1,
    state: 'in_progress',
    revision: 4,
    answers: {
      'question-reading-01': 'b',
    },
  },
};

export const demoPaths: PathSummary[] = [
  {
    id: 'path-toefl-01',
    title: 'TOEFL 90+ · 8 周进阶',
    track: 'toefl',
    status: 'active',
    progressPercent: 46,
    targetCompletionDate: '2026-08-28',
    currentMilestone: '第 4 周 · 阅读推断与听力结构',
    completedMilestones: 11,
    totalMilestones: 24,
  },
  {
    id: 'path-general-01',
    title: 'General 学术英语基础',
    track: 'general',
    status: 'active',
    progressPercent: 72,
    targetCompletionDate: '2026-07-31',
    currentMilestone: '复杂句与段落衔接',
    completedMilestones: 18,
    totalMilestones: 25,
  },
];

export const demoStudentDashboard: StudentDashboardData = {
  counts: { available: 3, dueSoon: 2, overdue: 0, awaitingFeedback: 1 },
  nextTaskItems: demoTasks.slice(0, 3),
  activePaths: demoPaths,
  weeklyMinutes: [32, 58, 46, 75, 38, 64, 41],
  streakDays: 6,
};

export const demoProgress: StudentProgressData = {
  from: '2026-06-12',
  to: '2026-07-11',
  assignedCount: 31,
  completedCount: 26,
  onTimeCount: 24,
  lateCount: 2,
  byKind: [
    { kind: 'lesson', assigned: 8, completed: 8, averageScorePercent: 91 },
    { kind: 'practice', assigned: 13, completed: 11, averageScorePercent: 84 },
    { kind: 'assessment', assigned: 5, completed: 4, averageScorePercent: 79 },
    { kind: 'writing', assigned: 5, completed: 3, averageScorePercent: 82 },
  ],
  weeklyScores: [74, 78, 76, 82, 84, 87],
};

export const demoFeedback: FeedbackItem[] = [
  {
    id: 'feedback-01',
    taskItemId: 'task-completed-01',
    attemptId: 'attempt-completed-01',
    taskTitle: '句子结构 · 从句辨析',
    score: 18,
    maxScore: 20,
    source: 'auto_scored',
    feedback: '定语从句判断稳定。建议复习非限定性从句中的标点使用。',
    returnedAt: '2026-07-09T08:30:00Z',
    readAt: null,
    rubric: [
      { label: '准确度', score: 9, maxScore: 10 },
      { label: '完成度', score: 9, maxScore: 10 },
    ],
  },
  {
    id: 'feedback-02',
    taskItemId: 'task-writing-previous',
    attemptId: 'attempt-writing-previous',
    taskTitle: '综合写作 · 校园交通政策',
    score: 24,
    maxScore: 30,
    source: 'teacher_confirmed',
    feedback: '论点提取准确，第二段需要更明确地连接听力反驳与阅读原观点。',
    returnedAt: '2026-07-07T13:20:00Z',
    readAt: '2026-07-07T14:00:00Z',
    rubric: [
      { label: '内容覆盖', score: 8, maxScore: 10 },
      { label: '组织结构', score: 7, maxScore: 10 },
      { label: '语言表达', score: 9, maxScore: 10 },
    ],
  },
];

export const demoSubmissions: SubmissionSummary[] = [
  {
    attemptId: 'attempt-grade-01',
    taskItemId: 'task-grade-01',
    studentMembershipId: 'student-01',
    studentDisplayName: '陈知夏',
    taskTitle: '独立写作 · 技术与教育',
    kind: 'writing',
    submittedAt: '2026-07-11T02:18:00Z',
    isLate: false,
    submissionSnapshotId: 'snapshot-grade-01',
  },
  {
    attemptId: 'attempt-grade-02',
    taskItemId: 'task-grade-02',
    studentMembershipId: 'student-02',
    studentDisplayName: '周予安',
    taskTitle: '综合写作 · 城市交通',
    kind: 'writing',
    submittedAt: '2026-07-10T15:42:00Z',
    isLate: true,
    submissionSnapshotId: 'snapshot-grade-02',
  },
  {
    attemptId: 'attempt-grade-03',
    taskItemId: 'task-grade-03',
    studentMembershipId: 'student-03',
    studentDisplayName: '宋嘉禾',
    taskTitle: '段落改写 · 信息整合',
    kind: 'writing',
    submittedAt: '2026-07-10T11:06:00Z',
    isLate: false,
    submissionSnapshotId: 'snapshot-grade-03',
  },
];

export const demoTeacherDashboard: TeacherDashboardData = {
  classCount: 4,
  studentCount: 68,
  awaitingGradeCount: 12,
  returnedThisWeekCount: 19,
  recentSubmissions: demoSubmissions,
};

export const demoClasses: ClassSummary[] = [
  {
    id: 'class-a2',
    name: 'TOEFL A2 冲刺班',
    code: 'TFL-A2',
    status: 'active',
    teacherCount: 2,
    studentCount: 22,
    completionRate: 86,
    nextDueAt: '2026-07-12T12:00:00Z',
  },
  {
    id: 'class-g1',
    name: 'General G1 学术基础',
    code: 'GEN-G1',
    status: 'active',
    teacherCount: 2,
    studentCount: 18,
    completionRate: 79,
    nextDueAt: '2026-07-14T12:00:00Z',
  },
  {
    id: 'class-writing',
    name: '写作精修小组',
    code: 'WRITE-03',
    status: 'active',
    teacherCount: 1,
    studentCount: 12,
    completionRate: 91,
    nextDueAt: '2026-07-13T14:00:00Z',
  },
];

export const demoStudents: StudentSummary[] = [
  {
    membershipId: 'student-01',
    displayName: '陈知夏',
    studentNumber: 'HL-26018',
    classNames: ['TOEFL A2 冲刺班'],
    activePathCount: 2,
    overdueTaskCount: 0,
    completionRate: 92,
    averageScore: 86,
    lastActiveAt: '2026-07-11T02:18:00Z',
  },
  {
    membershipId: 'student-02',
    displayName: '周予安',
    studentNumber: 'HL-26024',
    classNames: ['TOEFL A2 冲刺班', '写作精修小组'],
    activePathCount: 2,
    overdueTaskCount: 2,
    completionRate: 74,
    averageScore: 79,
    lastActiveAt: '2026-07-10T15:42:00Z',
  },
  {
    membershipId: 'student-03',
    displayName: '宋嘉禾',
    studentNumber: 'HL-26031',
    classNames: ['General G1 学术基础'],
    activePathCount: 1,
    overdueTaskCount: 1,
    completionRate: 81,
    averageScore: 83,
    lastActiveAt: '2026-07-10T11:06:00Z',
  },
  {
    membershipId: 'student-04',
    displayName: '许一川',
    studentNumber: 'HL-26036',
    classNames: ['General G1 学术基础'],
    activePathCount: 1,
    overdueTaskCount: 0,
    completionRate: 88,
    averageScore: 89,
    lastActiveAt: '2026-07-11T01:38:00Z',
  },
];

export const demoMemberships: Membership[] = [
  {
    id: 'member-01',
    email: 'xiaoran@example.com',
    displayName: '林晓然',
    status: 'active',
    roles: ['student', 'teacher', 'admin'],
    joinedAt: '2026-04-02T08:00:00Z',
  },
  {
    id: 'member-02',
    email: 'zhou.teacher@example.com',
    displayName: '周老师',
    status: 'active',
    roles: ['teacher'],
    joinedAt: '2026-03-18T08:00:00Z',
  },
  {
    id: 'member-03',
    email: 'chen.zhixia@example.com',
    displayName: '陈知夏',
    status: 'active',
    roles: ['student'],
    joinedAt: '2026-05-09T08:00:00Z',
  },
  {
    id: 'member-04',
    email: 'new.student@example.com',
    displayName: '待加入学生',
    status: 'invited',
    roles: ['student'],
    joinedAt: null,
  },
];

export const demoCatalog: CatalogItem[] = [
  {
    id: 'catalog-01',
    type: 'content',
    title: '城市公共空间：阅读材料',
    slug: 'urban-public-space',
    ownership: 'tenant',
    publicationState: 'published',
    versionNumber: 3,
    updatedAt: '2026-07-10T09:20:00Z',
    kind: 'passage',
  },
  {
    id: 'catalog-02',
    type: 'task',
    title: 'TOEFL 阅读 · 推断题专项',
    slug: 'toefl-reading-inference',
    ownership: 'tenant',
    publicationState: 'published',
    versionNumber: 3,
    updatedAt: '2026-07-09T10:10:00Z',
    kind: 'practice',
  },
  {
    id: 'catalog-03',
    type: 'question',
    title: '公共空间推断题 Q1',
    slug: 'public-space-inference-q1',
    ownership: 'tenant',
    publicationState: 'draft',
    versionNumber: 4,
    updatedAt: '2026-07-11T01:32:00Z',
    kind: 'single_choice',
  },
  {
    id: 'catalog-04',
    type: 'path',
    title: 'TOEFL 90+ · 8 周进阶',
    slug: 'toefl-90-eight-weeks',
    ownership: 'platform',
    publicationState: 'published',
    versionNumber: 6,
    updatedAt: '2026-07-06T08:00:00Z',
    kind: 'toefl',
  },
  {
    id: 'catalog-05',
    type: 'content',
    title: '学术词汇核心清单',
    slug: 'academic-vocabulary-core',
    ownership: 'platform',
    publicationState: 'published',
    versionNumber: 8,
    updatedAt: '2026-07-04T08:00:00Z',
    kind: 'lesson',
  },
];
